import type { Metadata } from "next";
import "antd/dist/reset.css";
import "./globals.css";
import AntdProvider from "./antd-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body className="antialiased">
        <AntdProvider>
          {children}
        </AntdProvider>
      </body>
    </html>
  );
}
